### ISSUE TITLE
Split Free and Paid

### ISSUE THREAD

**Issue by rakosi2** [Myrkie/BoothWatcher#1]
Make two new arrays in the config to add WebHooks for just free and another for everything else.

**Comment by Myrkie** [comment]
can work on it next time im free though ill keep it as a optional config.

**Comment by Sighyu** [comment]
:painpeko:

**Comment by Myrkie** [comment]
going to be awhile until I can do anything here as, I am rather burnt out of coding, this code base is not very friendly and was never designed for a split webhook🤣

**Comment by Sighyu** [comment]
> this code base is not very friendly and was never designed for a split webhook🤣

say hello to my little friend called string.split

**Comment by Myrkie** [comment]
> > this code base is not very friendly and was never designed for a split webhook🤣
> 
> say hello to my little friend called string.split

yes string.split life is nice though

**Comment by Sighyu** [comment]
> > > this code base is not very friendly and was never designed for a split webhook🤣
> > 
> > 
> > say hello to my little friend called string.split
> 
> yes string.split life is nice though

truly screw the haters

**Comment by Myrkie** [comment]
closing this as I really don't have enough time to completely rewrite this, at this point im adding simple features and keeping it functional whenever the booth website updates.
